### PR TITLE
Remove txt from filtered suffixes

### PR DESCRIPTION
**Pull request by jspricke**
This allows to search in CMakeLists.txt as well.

### CODE REVIEW

**Comment by stapelberg** [comment]
Instead of blanket-approving all txt files, could you only whitelist CMakeLists.txt please?

**Comment by jspricke** [comment]
Like this?

**Comment by stapelberg** [comment]
Thanks for your patience with this PR — I’ve been busy with travels the last few weeks.

The code itself looks good, but I noticed that it wasn’t formatted using `gofmt`. Could you please do that? We want all code to be formatted using `gofmt`. For many editors, there are plugins which automate this, see also https://blog.golang.org/go-fmt-your-code

I also took this opportunity to also add a `.travis.yml` which ensures contributions are properly formatted and don’t break existing tests. Sorry that this hasn’t been around earlier; it would have provided you much quicker feedback :).

Thanks!

**Comment by jspricke** [comment]
Done :).

**Pull request merged**
